//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSDIndestructibles3.Web.SolicitudServicioServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudServicioDTO", Namespace="http://schemas.datacontract.org/2004/07/DSDIndestructibles3.Entities")]
    [System.SerializableAttribute()]
    public partial class SolicitudServicioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapacitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapacitadoCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CapacitadoFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapacitadoNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComercioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MotivoSolicitudIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenalizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenalizadoDescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieFisicoAtnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerieVirtualAtnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SolicitudServicioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TerminalInstaladoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerminalSolicitadoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsrModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsrRegField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Capacitado {
            get {
                return this.CapacitadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CapacitadoField, value) != true)) {
                    this.CapacitadoField = value;
                    this.RaisePropertyChanged("Capacitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CapacitadoCargo {
            get {
                return this.CapacitadoCargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CapacitadoCargoField, value) != true)) {
                    this.CapacitadoCargoField = value;
                    this.RaisePropertyChanged("CapacitadoCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CapacitadoFecha {
            get {
                return this.CapacitadoFechaField;
            }
            set {
                if ((this.CapacitadoFechaField.Equals(value) != true)) {
                    this.CapacitadoFechaField = value;
                    this.RaisePropertyChanged("CapacitadoFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CapacitadoNombres {
            get {
                return this.CapacitadoNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.CapacitadoNombresField, value) != true)) {
                    this.CapacitadoNombresField = value;
                    this.RaisePropertyChanged("CapacitadoNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComercioId {
            get {
                return this.ComercioIdField;
            }
            set {
                if ((this.ComercioIdField.Equals(value) != true)) {
                    this.ComercioIdField = value;
                    this.RaisePropertyChanged("ComercioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaMod {
            get {
                return this.FechaModField;
            }
            set {
                if ((this.FechaModField.Equals(value) != true)) {
                    this.FechaModField = value;
                    this.RaisePropertyChanged("FechaMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReg {
            get {
                return this.FechaRegField;
            }
            set {
                if ((this.FechaRegField.Equals(value) != true)) {
                    this.FechaRegField = value;
                    this.RaisePropertyChanged("FechaReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MotivoSolicitudId {
            get {
                return this.MotivoSolicitudIdField;
            }
            set {
                if ((this.MotivoSolicitudIdField.Equals(value) != true)) {
                    this.MotivoSolicitudIdField = value;
                    this.RaisePropertyChanged("MotivoSolicitudId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senalizado {
            get {
                return this.SenalizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.SenalizadoField, value) != true)) {
                    this.SenalizadoField = value;
                    this.RaisePropertyChanged("Senalizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenalizadoDescripcion {
            get {
                return this.SenalizadoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.SenalizadoDescripcionField, value) != true)) {
                    this.SenalizadoDescripcionField = value;
                    this.RaisePropertyChanged("SenalizadoDescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieFisicoAtn {
            get {
                return this.SerieFisicoAtnField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieFisicoAtnField, value) != true)) {
                    this.SerieFisicoAtnField = value;
                    this.RaisePropertyChanged("SerieFisicoAtn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerieVirtualAtn {
            get {
                return this.SerieVirtualAtnField;
            }
            set {
                if ((object.ReferenceEquals(this.SerieVirtualAtnField, value) != true)) {
                    this.SerieVirtualAtnField = value;
                    this.RaisePropertyChanged("SerieVirtualAtn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SolicitudServicioId {
            get {
                return this.SolicitudServicioIdField;
            }
            set {
                if ((this.SolicitudServicioIdField.Equals(value) != true)) {
                    this.SolicitudServicioIdField = value;
                    this.RaisePropertyChanged("SolicitudServicioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TerminalInstaladoId {
            get {
                return this.TerminalInstaladoIdField;
            }
            set {
                if ((this.TerminalInstaladoIdField.Equals(value) != true)) {
                    this.TerminalInstaladoIdField = value;
                    this.RaisePropertyChanged("TerminalInstaladoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalSolicitadoId {
            get {
                return this.TerminalSolicitadoIdField;
            }
            set {
                if ((this.TerminalSolicitadoIdField.Equals(value) != true)) {
                    this.TerminalSolicitadoIdField = value;
                    this.RaisePropertyChanged("TerminalSolicitadoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UsrMod {
            get {
                return this.UsrModField;
            }
            set {
                if ((this.UsrModField.Equals(value) != true)) {
                    this.UsrModField = value;
                    this.RaisePropertyChanged("UsrMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsrReg {
            get {
                return this.UsrRegField;
            }
            set {
                if ((this.UsrRegField.Equals(value) != true)) {
                    this.UsrRegField = value;
                    this.RaisePropertyChanged("UsrReg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SolicitudServicioServices.ISolicitudServicio")]
    public interface ISolicitudServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Registrar", ReplyAction="http://tempuri.org/ISolicitudServicio/RegistrarResponse")]
        void Registrar(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Registrar", ReplyAction="http://tempuri.org/ISolicitudServicio/RegistrarResponse")]
        System.Threading.Tasks.Task RegistrarAsync(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Actualizar", ReplyAction="http://tempuri.org/ISolicitudServicio/ActualizarResponse")]
        void Actualizar(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Actualizar", ReplyAction="http://tempuri.org/ISolicitudServicio/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Eliminar", ReplyAction="http://tempuri.org/ISolicitudServicio/EliminarResponse")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Eliminar", ReplyAction="http://tempuri.org/ISolicitudServicio/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Obtener", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerResponse")]
        DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO Obtener(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/Obtener", ReplyAction="http://tempuri.org/ISolicitudServicio/ObtenerResponse")]
        System.Threading.Tasks.Task<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO> ObtenerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarBandeja", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarBandejaResponse")]
        System.Collections.Generic.List<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO> ListarBandeja(System.DateTime fechaDesde, System.DateTime fechaHasta, string estado, int empresaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitudServicio/ListarBandeja", ReplyAction="http://tempuri.org/ISolicitudServicio/ListarBandejaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO>> ListarBandejaAsync(System.DateTime fechaDesde, System.DateTime fechaHasta, string estado, int empresaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitudServicioChannel : DSDIndestructibles3.Web.SolicitudServicioServices.ISolicitudServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudServicioClient : System.ServiceModel.ClientBase<DSDIndestructibles3.Web.SolicitudServicioServices.ISolicitudServicio>, DSDIndestructibles3.Web.SolicitudServicioServices.ISolicitudServicio {
        
        public SolicitudServicioClient() {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Registrar(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE) {
            base.Channel.Registrar(oSolicitudServicioBE);
        }
        
        public System.Threading.Tasks.Task RegistrarAsync(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE) {
            return base.Channel.RegistrarAsync(oSolicitudServicioBE);
        }
        
        public void Actualizar(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE) {
            base.Channel.Actualizar(oSolicitudServicioBE);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO oSolicitudServicioBE) {
            return base.Channel.ActualizarAsync(oSolicitudServicioBE);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO Obtener(int id) {
            return base.Channel.Obtener(id);
        }
        
        public System.Threading.Tasks.Task<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO> ObtenerAsync(int id) {
            return base.Channel.ObtenerAsync(id);
        }
        
        public System.Collections.Generic.List<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO> ListarBandeja(System.DateTime fechaDesde, System.DateTime fechaHasta, string estado, int empresaId) {
            return base.Channel.ListarBandeja(fechaDesde, fechaHasta, estado, empresaId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DSDIndestructibles3.Web.SolicitudServicioServices.SolicitudServicioDTO>> ListarBandejaAsync(System.DateTime fechaDesde, System.DateTime fechaHasta, string estado, int empresaId) {
            return base.Channel.ListarBandejaAsync(fechaDesde, fechaHasta, estado, empresaId);
        }
    }
}
