//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSDIndestructibles3.Web.Services.Seguridad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Seguridad.ISeguridad")]
    public interface ISeguridad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridad/Login", ReplyAction="http://tempuri.org/ISeguridad/LoginResponse")]
        void Login(string username, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridad/Login", ReplyAction="http://tempuri.org/ISeguridad/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string username, string clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISeguridadChannel : DSDIndestructibles3.Web.Services.Seguridad.ISeguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<DSDIndestructibles3.Web.Services.Seguridad.ISeguridad>, DSDIndestructibles3.Web.Services.Seguridad.ISeguridad {
        
        public SeguridadClient() {
        }
        
        public SeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Login(string username, string clave) {
            base.Channel.Login(username, clave);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username, string clave) {
            return base.Channel.LoginAsync(username, clave);
        }
    }
}
