//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSDIndestructibles3.Web.Services.Terminal {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TerminalDTO", Namespace="http://schemas.datacontract.org/2004/07/DSDIndestructibles3.Entities")]
    [System.SerializableAttribute()]
    public partial class TerminalDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComunicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TerminalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsrModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsrRegField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comunicacion {
            get {
                return this.ComunicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ComunicacionField, value) != true)) {
                    this.ComunicacionField = value;
                    this.RaisePropertyChanged("Comunicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMod {
            get {
                return this.FechaModField;
            }
            set {
                if ((this.FechaModField.Equals(value) != true)) {
                    this.FechaModField = value;
                    this.RaisePropertyChanged("FechaMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReg {
            get {
                return this.FechaRegField;
            }
            set {
                if ((this.FechaRegField.Equals(value) != true)) {
                    this.FechaRegField = value;
                    this.RaisePropertyChanged("FechaReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TerminalId {
            get {
                return this.TerminalIdField;
            }
            set {
                if ((this.TerminalIdField.Equals(value) != true)) {
                    this.TerminalIdField = value;
                    this.RaisePropertyChanged("TerminalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsrMod {
            get {
                return this.UsrModField;
            }
            set {
                if ((this.UsrModField.Equals(value) != true)) {
                    this.UsrModField = value;
                    this.RaisePropertyChanged("UsrMod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsrReg {
            get {
                return this.UsrRegField;
            }
            set {
                if ((this.UsrRegField.Equals(value) != true)) {
                    this.UsrRegField = value;
                    this.RaisePropertyChanged("UsrReg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Terminal.ITerminalService")]
    public interface ITerminalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/GetAll", ReplyAction="http://tempuri.org/ITerminalService/GetAllResponse")]
        System.Collections.Generic.List<DSDIndestructibles3.Web.Services.Terminal.TerminalDTO> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITerminalService/GetAll", ReplyAction="http://tempuri.org/ITerminalService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DSDIndestructibles3.Web.Services.Terminal.TerminalDTO>> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITerminalServiceChannel : DSDIndestructibles3.Web.Services.Terminal.ITerminalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TerminalServiceClient : System.ServiceModel.ClientBase<DSDIndestructibles3.Web.Services.Terminal.ITerminalService>, DSDIndestructibles3.Web.Services.Terminal.ITerminalService {
        
        public TerminalServiceClient() {
        }
        
        public TerminalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TerminalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DSDIndestructibles3.Web.Services.Terminal.TerminalDTO> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DSDIndestructibles3.Web.Services.Terminal.TerminalDTO>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
