//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSDIndestructibles3.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int PerfilId { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<int> UsrReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> UsrMod { get; set; }
    }
}
