//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSDIndestructibles3.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudServicio
    {
        public int SolicitudServicioId { get; set; }
        public Nullable<int> ComercioId { get; set; }
        public Nullable<int> MotivoSolicitudId { get; set; }
        public Nullable<int> TerminalSolicitadoId { get; set; }
        public Nullable<int> TerminalInstaladoId { get; set; }
        public string SerieFisicoAtn { get; set; }
        public string SerieVirtualAtn { get; set; }
        public string Capacitado { get; set; }
        public string CapacitadoNombres { get; set; }
        public string CapacitadoCargo { get; set; }
        public Nullable<System.DateTime> CapacitadoFecha { get; set; }
        public string Senalizado { get; set; }
        public string SenalizadoDescripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public Nullable<int> UsrReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> UsrMod { get; set; }
    }
}
